/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.lifstools.mztab2.model.Parameter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ColumnParameterMapping
 */
class ColumnParameterMappingTest {
    private final ColumnParameterMapping model = new ColumnParameterMapping();

    /**
     * Model tests for ColumnParameterMapping
     */
    @Test
    void testColumnParameterMapping() {
        // TODO: test ColumnParameterMapping
    }

    /**
     * Test the property 'columnName'
     */
    @Test
    void columnNameTest() {
        // TODO: test columnName
    }

    /**
     * Test the property 'param'
     */
    @Test
    void paramTest() {
        // TODO: test param
    }

}
