/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Assay;
import org.lifstools.mztab2.model.CV;
import org.lifstools.mztab2.model.ColumnParameterMapping;
import org.lifstools.mztab2.model.Contact;
import org.lifstools.mztab2.model.Database;
import org.lifstools.mztab2.model.Instrument;
import org.lifstools.mztab2.model.MsRun;
import org.lifstools.mztab2.model.Parameter;
import org.lifstools.mztab2.model.Publication;
import org.lifstools.mztab2.model.Sample;
import org.lifstools.mztab2.model.SampleProcessing;
import org.lifstools.mztab2.model.Software;
import org.lifstools.mztab2.model.StudyVariable;
import org.lifstools.mztab2.model.Uri;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Metadata
 */
class MetadataTest {
    private final Metadata model = new Metadata();

    /**
     * Model tests for Metadata
     */
    @Test
    void testMetadata() {
        // TODO: test Metadata
    }

    /**
     * Test the property 'prefix'
     */
    @Test
    void prefixTest() {
        // TODO: test prefix
    }

    /**
     * Test the property 'mzTabVersion'
     */
    @Test
    void mzTabVersionTest() {
        // TODO: test mzTabVersion
    }

    /**
     * Test the property 'mzTabID'
     */
    @Test
    void mzTabIDTest() {
        // TODO: test mzTabID
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'contact'
     */
    @Test
    void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'publication'
     */
    @Test
    void publicationTest() {
        // TODO: test publication
    }

    /**
     * Test the property 'uri'
     */
    @Test
    void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'externalStudyUri'
     */
    @Test
    void externalStudyUriTest() {
        // TODO: test externalStudyUri
    }

    /**
     * Test the property 'instrument'
     */
    @Test
    void instrumentTest() {
        // TODO: test instrument
    }

    /**
     * Test the property 'quantificationMethod'
     */
    @Test
    void quantificationMethodTest() {
        // TODO: test quantificationMethod
    }

    /**
     * Test the property 'sample'
     */
    @Test
    void sampleTest() {
        // TODO: test sample
    }

    /**
     * Test the property 'sampleProcessing'
     */
    @Test
    void sampleProcessingTest() {
        // TODO: test sampleProcessing
    }

    /**
     * Test the property 'software'
     */
    @Test
    void softwareTest() {
        // TODO: test software
    }

    /**
     * Test the property 'derivatizationAgent'
     */
    @Test
    void derivatizationAgentTest() {
        // TODO: test derivatizationAgent
    }

    /**
     * Test the property 'msRun'
     */
    @Test
    void msRunTest() {
        // TODO: test msRun
    }

    /**
     * Test the property 'assay'
     */
    @Test
    void assayTest() {
        // TODO: test assay
    }

    /**
     * Test the property 'studyVariable'
     */
    @Test
    void studyVariableTest() {
        // TODO: test studyVariable
    }

    /**
     * Test the property 'custom'
     */
    @Test
    void customTest() {
        // TODO: test custom
    }

    /**
     * Test the property 'cv'
     */
    @Test
    void cvTest() {
        // TODO: test cv
    }

    /**
     * Test the property 'smallMoleculeQuantificationUnit'
     */
    @Test
    void smallMoleculeQuantificationUnitTest() {
        // TODO: test smallMoleculeQuantificationUnit
    }

    /**
     * Test the property 'smallMoleculeFeatureQuantificationUnit'
     */
    @Test
    void smallMoleculeFeatureQuantificationUnitTest() {
        // TODO: test smallMoleculeFeatureQuantificationUnit
    }

    /**
     * Test the property 'smallMoleculeIdentificationReliability'
     */
    @Test
    void smallMoleculeIdentificationReliabilityTest() {
        // TODO: test smallMoleculeIdentificationReliability
    }

    /**
     * Test the property 'database'
     */
    @Test
    void databaseTest() {
        // TODO: test database
    }

    /**
     * Test the property 'idConfidenceMeasure'
     */
    @Test
    void idConfidenceMeasureTest() {
        // TODO: test idConfidenceMeasure
    }

    /**
     * Test the property 'colunitSmallMolecule'
     */
    @Test
    void colunitSmallMoleculeTest() {
        // TODO: test colunitSmallMolecule
    }

    /**
     * Test the property 'colunitSmallMoleculeFeature'
     */
    @Test
    void colunitSmallMoleculeFeatureTest() {
        // TODO: test colunitSmallMoleculeFeature
    }

    /**
     * Test the property 'colunitSmallMoleculeEvidence'
     */
    @Test
    void colunitSmallMoleculeEvidenceTest() {
        // TODO: test colunitSmallMoleculeEvidence
    }

}
