/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Instrument;
import org.lifstools.mztab2.model.Parameter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MsRun
 */
class MsRunTest {
    private final MsRun model = new MsRun();

    /**
     * Model tests for MsRun
     */
    @Test
    void testMsRun() {
        // TODO: test MsRun
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'location'
     */
    @Test
    void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'instrumentRef'
     */
    @Test
    void instrumentRefTest() {
        // TODO: test instrumentRef
    }

    /**
     * Test the property 'format'
     */
    @Test
    void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'idFormat'
     */
    @Test
    void idFormatTest() {
        // TODO: test idFormat
    }

    /**
     * Test the property 'fragmentationMethod'
     */
    @Test
    void fragmentationMethodTest() {
        // TODO: test fragmentationMethod
    }

    /**
     * Test the property 'scanPolarity'
     */
    @Test
    void scanPolarityTest() {
        // TODO: test scanPolarity
    }

    /**
     * Test the property 'hash'
     */
    @Test
    void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'hashMethod'
     */
    @Test
    void hashMethodTest() {
        // TODO: test hashMethod
    }

}
