/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.lifstools.mztab2.model.Parameter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OptColumnMapping
 */
class OptColumnMappingTest {
    private final OptColumnMapping model = new OptColumnMapping();

    /**
     * Model tests for OptColumnMapping
     */
    @Test
    void testOptColumnMapping() {
        // TODO: test OptColumnMapping
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'param'
     */
    @Test
    void paramTest() {
        // TODO: test param
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

}
