/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Comment;
import org.lifstools.mztab2.model.OptColumnMapping;
import org.lifstools.mztab2.model.Parameter;
import org.lifstools.mztab2.model.SpectraRef;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SmallMoleculeEvidence
 */
class SmallMoleculeEvidenceTest {
    private final SmallMoleculeEvidence model = new SmallMoleculeEvidence();

    /**
     * Model tests for SmallMoleculeEvidence
     */
    @Test
    void testSmallMoleculeEvidence() {
        // TODO: test SmallMoleculeEvidence
    }

    /**
     * Test the property 'prefix'
     */
    @Test
    void prefixTest() {
        // TODO: test prefix
    }

    /**
     * Test the property 'headerPrefix'
     */
    @Test
    void headerPrefixTest() {
        // TODO: test headerPrefix
    }

    /**
     * Test the property 'smeId'
     */
    @Test
    void smeIdTest() {
        // TODO: test smeId
    }

    /**
     * Test the property 'evidenceInputId'
     */
    @Test
    void evidenceInputIdTest() {
        // TODO: test evidenceInputId
    }

    /**
     * Test the property 'databaseIdentifier'
     */
    @Test
    void databaseIdentifierTest() {
        // TODO: test databaseIdentifier
    }

    /**
     * Test the property 'chemicalFormula'
     */
    @Test
    void chemicalFormulaTest() {
        // TODO: test chemicalFormula
    }

    /**
     * Test the property 'smiles'
     */
    @Test
    void smilesTest() {
        // TODO: test smiles
    }

    /**
     * Test the property 'inchi'
     */
    @Test
    void inchiTest() {
        // TODO: test inchi
    }

    /**
     * Test the property 'chemicalName'
     */
    @Test
    void chemicalNameTest() {
        // TODO: test chemicalName
    }

    /**
     * Test the property 'uri'
     */
    @Test
    void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'derivatizedForm'
     */
    @Test
    void derivatizedFormTest() {
        // TODO: test derivatizedForm
    }

    /**
     * Test the property 'adductIon'
     */
    @Test
    void adductIonTest() {
        // TODO: test adductIon
    }

    /**
     * Test the property 'expMassToCharge'
     */
    @Test
    void expMassToChargeTest() {
        // TODO: test expMassToCharge
    }

    /**
     * Test the property 'charge'
     */
    @Test
    void chargeTest() {
        // TODO: test charge
    }

    /**
     * Test the property 'theoreticalMassToCharge'
     */
    @Test
    void theoreticalMassToChargeTest() {
        // TODO: test theoreticalMassToCharge
    }

    /**
     * Test the property 'spectraRef'
     */
    @Test
    void spectraRefTest() {
        // TODO: test spectraRef
    }

    /**
     * Test the property 'identificationMethod'
     */
    @Test
    void identificationMethodTest() {
        // TODO: test identificationMethod
    }

    /**
     * Test the property 'msLevel'
     */
    @Test
    void msLevelTest() {
        // TODO: test msLevel
    }

    /**
     * Test the property 'idConfidenceMeasure'
     */
    @Test
    void idConfidenceMeasureTest() {
        // TODO: test idConfidenceMeasure
    }

    /**
     * Test the property 'rank'
     */
    @Test
    void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'opt'
     */
    @Test
    void optTest() {
        // TODO: test opt
    }

    /**
     * Test the property 'comment'
     */
    @Test
    void commentTest() {
        // TODO: test comment
    }

}
