= mzTab Swagger API
Nils Hoffmann <nils.hoffmann@isas.de>

Build status: image:https://travis-ci.org/nilshoffmann/jmzTab-m.svg?branch=master["Build Status", link="https://travis-ci.org/nilshoffmann/jmzTab-m"]

This project defines the structure of an mzTab document based on JSON-Schema
and Swagger https://swagger.io/.

Swagger provides many templates to generate client / server implementations
based on a Swagger yaml or json definition.

This mechanism can be used to generate the domain-specific model classes in
any of the supported languages, omitting the web-specific parts.

The https://editor.swagger.io/[Swagger editor] can be used to import the file,
edit it with assistance and preview, and export it after editing. It additionally 
supports the generation of server and client code to represent the mzTab object structure.

To launch the editor via https://www.docker.com/[Docker] on Unix, use the script
`run-swagger-editor.sh` in this directory.

The swagger API definition is in the following file: `api/src/main/resources/mzTab_m_swagger.yml`.

You can open it in the Swagger Editor via File -> Import File. If you are done editing, go to File -> Download YAML and save the file at the location of the mzTab_m_swagger.yml file, thereby replacing the original file.

You can create server and client code in a multitude of languages from the Generate Server and Generate Client menu items.

== Generating client code from the command-line

In order to build the client code and run the unit tests, execute the following command from a terminal:

	./mvnw install

This generates the necessary domain specific code for a number of different languages, e.g. for Python, JAVA and R.
In general, any language and framework for which swagger-codegen has templates available may be used. For details, please 
look at the `api/pom.xml` file and at the https://github.com/swagger-api/swagger-codegen[swagger-codegen repository and documentation].

The generated code is available in the zip archives below the `api/target` directory:

. mztab-java
. mztab-api-python
. mztab-api-r

The generated client libraries only contain the basid domain object code. Parsing from mzTab and writing to mzTab still need to be 
implementd separately. 

== Running a validation with the command-line interface
The `cli` sub-project provides a command line interface for validation of files using the mzTab 1.1 draft validator. 

NOTE: Currently, we do not plan to provide a CLI-based validator for mzTab 1.0, since that is still being provided by the original https://github.com/PRIDE-Utilities/jmzTab[jmzTab project].

After building the project as mentioned above with `./mvnw install`, the `cli/target` folder will contain the `cli-<version>-jmztabm-deployment.zip` file.

In order to run the validator, unzip that file, change into the unzipped `cli` folder and run

  java -jar mzTabCLI.jar

to see the available options.

To validate a particular file with a given level (one of: Info, Warn, Error), run

  java -jar mzTabCLI.jar -check inFile=/path/to/your/file.mztab -level Warn

