= mzTab Swagger API
Nils Hoffmann <nils.hoffmann@isas.de>

Build status: image:https://travis-ci.org/nilshoffmann/jmzTab-m.svg?branch=master["Build Status", link="https://travis-ci.org/nilshoffmann/jmzTab-m"]

This project defines the structure of an mzTab document based on JSON-Schema
and Swagger https://swagger.io/.

Swagger provides many templates to generate client / server implementations
based on a Swagger yaml or json definition.

This mechanism can be used to generate the domain-specific model classes in
any of the supported languages, omitting the web-specific parts.

The https://editor.swagger.io/[Swagger editor] can be used to import the file,
edit it with assistance and preview, and export it after editing. It additionally 
supports the generation of server and client code to represent the mzTab object structure.

To launch the editor via https://www.docker.com/[Docker] on Unix, use the script
`run-swagger-editor.sh` in this directory.

The swagger API definition is in the following file: `api/src/main/resources/mzTab_m_swagger.yml`.

You can open it in the Swagger Editor via File -> Import File. If you are done editing, go to File -> Download YAML and save the file at the location of the mzTab_m_swagger.yml file, thereby replacing the original file.

You can create server and client code in a multitude of languages from the Generate Server and Generate Client menu items.

== Building the project and generating client code from the command-line

In order to build the client code and run the unit tests, execute the following command from a terminal:

	./mvnw install

This generates the necessary domain specific code for a number of different languages, e.g. for Python, JAVA and R.
In general, any language and framework for which swagger-codegen has templates available may be used. For details, please 
look at the `api/pom.xml` file and at the https://github.com/swagger-api/swagger-codegen[swagger-codegen repository and documentation].

The generated code is available in the zip archives below the `api/target` directory:

. mztab-java
. mztab-api-python
. mztab-api-r

The generated client libraries only contain the basic domain object code. Parsing from mzTab and writing to mzTab still need to be 
implemented separately. 

== Running a validation with the command-line interface
The `cli` sub-project provides a command line interface for validation of files using the mzTab 1.1 draft validator. 

NOTE: Currently, we do not plan to provide a CLI-based validator for mzTab 1.0, since that is still being provided by the original https://github.com/PRIDE-Utilities/jmzTab[jmzTab project].

After building the project as mentioned above with `./mvnw install`, the `cli/target` folder will contain the `cli-<version>-jmztabm-deployment.zip` file.

In order to run the validator, unzip that file, change into the unzipped `cli` folder and run

  java -jar mzTabCLI.jar

to see the available options.

To validate a particular file with a given level (one of: Info, Warn, Error), run

  java -jar mzTabCLI.jar -check inFile=/path/to/your/file.mztab -level Warn

== Running the Web Application for Validation
The web-application is based on https://projects.spring.io/spring-boot/[Spring-Boot], http://www.thymeleaf.org/[Thymeleaf], https://jquery.com/[jQuery], https://datatables.net/[jQuery Datatables] and https://getbootstrap.com/[Bootstrap 4].
The `web` sub-project builds and bundles all necessary dependencies and resources into a stand-alone, executable JAR file that can be run as follows (please replace <VERSION> with the correct one)

  ./mztabvalidation-<VERSION>.jar

This will start the application with a default configuration, running on http port 8083. 
The application can then be accessed from your web browser at

  http://localhost:8083

== Building the Web Application Docker Image
If you want to run the web application as a docker container, you can build it as follows:

  ./mvnw -Pdocker install

This will build a Docker container for the webapplication and will make it locally available to be run by docker.

  docker image ls
  REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
  isas/mztab-validator-webapp   1.0.0-SNAPSHOT      b87d4683db50        About an hour ago   472MB

Please note that the base image we use is quite large (for details, see `web/Dockerfile`), but also includes monitoring utilities and automatic scaling and limiting of the 
internal JVMs memory based on the amount of memory allocated for the container by Docker.

To run the web application as a Docker container, type in the following (replacing <VERSION> with the current project version, i.e. the TAG version displayed by `docker image ls`):

  docker run -it --rm --name mztabvalidator -p 8080:8083 -m 150M isas/mztab-validator-webapp:<VERSION>

== References

This project is based on and uses code that was developed for the https://github.com/PRIDE-Utilities/jmzTab[original jmzTab project]:

http://onlinelibrary.wiley.com/doi/10.1002/pmic.201300560/abstract[Qing-Wei Xu et al., Proteomics 2014; Jun;14(11):1328-32.] http://onlinelibrary.wiley.com/doi/10.1002/pmic.201300560/pdf[PDF File.] https://www.ncbi.nlm.nih.gov/pubmed/24659499[PubMed record.]

