= mzTab 2.0 for Metabolomics Reader, Writer and Validator
Nils Hoffmann <nils.hoffmann@isas.de>

Build status: image:https://travis-ci.org/nilshoffmann/jmzTab-m.svg?branch=master["Build Status", link="https://travis-ci.org/nilshoffmann/jmzTab-m"]

This project is the reference reader, writer and validator implementation for mzTab 2.0+, based on the https://github.com/PRIDE-Utilities/jmztab[jmztab project].

The latest draft version of the mzTab spec is available https://github.com/HUPO-PSI/mzTab/blob/master/specification_document/1_1_draft_specs/mzTab_format_specification_1_1-M_draft.adoc[here].

The web-based validator application is available https://github.com/nilshoffmann/jmzTab-m-webapp[here].

== Building the project and generating client code from the command-line

In order to build the client code and run the unit tests, execute the following command from a terminal:

	./mvnw install

This generates the necessary domain specific code for a number of different languages, e.g. for Python, JAVA and R.
In general, any language and framework for which swagger-codegen has templates available may be used. For details, please 
look at the `api/pom.xml` file and at the https://github.com/swagger-api/swagger-codegen[swagger-codegen repository and documentation].

The generated code is available in the zip archives below the `api/target` directory:

. mztab-java
. mztab-api-python
. mztab-api-r

The generated client libraries only contain the basic domain object code. Parsing from mzTab and writing to mzTab still need to be 
implemented separately. 

== Running a validation with the command-line interface
The `cli` sub-project provides a command line interface for validation of files using the mzTab 2.0 draft validator. 

NOTE: Currently, we do not plan to provide a CLI-based validator for mzTab 1.0, since that is still being provided by the original https://github.com/PRIDE-Utilities/jmzTab[jmzTab project].

After building the project as mentioned above with `./mvnw install`, the `cli/target` folder will contain the `cli-<version>-jmztabm-deployment.zip` file.

In order to run the validator, unzip that file, change into the unzipped `cli` folder and run

  java -jar mzTabCLI.jar

to see the available options.

To validate a particular file with a given level (one of: Info, Warn, Error, where Info includes Warn and Error), run

  java -jar mzTabCLI.jar -check inFile=/path/to/your/file.mztab -level Warn

== Running the Web Application for Validation

The validator web application has been moved into a separate project: https://github.com/nilshoffmann/jmzTab-m-webapp

== Using the project code via Maven Central

The library artifacts are available as SNAPSHOT (development versions) from Sonatype's OSSRH repository. 
If you want to use them, add the following to your own Maven pom file:

  <repositories>
    <repository>
      <name>Sonatype Snapshot Repository</name>
      <id>oss-sonatype-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
   ...
  </repositories>

The project coordinates for the api module are 

    <dependency>
      <groupId>de.isas.mztab</groupId>
      <artifactId>jmztabm-api</artifactId>
      <version>${jmztabm.version}</version>
      <type>jar</type>
    </dependency>

and

    <dependency>
      <groupId>de.isas.mztab</groupId>
      <artifactId>jmztabm-io</artifactId>
      <version>${jmztabm.version}</version>
      <type>jar</type>
    </dependency>

for the io module, where `jmztab.version` is the version of jmztabm you wish to use, e.g. for a SNAPSHOT version:

  <properties>
    <jmztabm.version>0.9.0-SNAPSHOT</jmztabm.version>
  </properties>

as defined in the properties section of your pom file.

The SNAPSHOTS are also available from https://oss.sonatype.org/content/repositories/snapshots/de/isas/mztab/.

== Editing the Swagger Spec
This project defines the structure of an mzTab document based on JSON-Schema
and Swagger https://swagger.io/.

Swagger provides many templates to generate client / server implementations
based on a Swagger yaml or json definition.

This mechanism can be used to generate the domain-specific model classes in
any of the supported languages, omitting the web-specific parts.

The https://editor.swagger.io/[Swagger editor] can be used to import the file,
edit it with assistance and preview, and export it after editing. It additionally 
supports the generation of server and client code to represent the mzTab object structure.

To launch the editor via https://www.docker.com/[Docker] on Unix, use the script
`run-swagger-editor.sh` in this directory.

The swagger API definition is in the following file: `api/src/main/resources/mzTab_m_swagger.yml`.

You can open it in the Swagger Editor via File -> Import File. If you are done editing, go to File -> Download YAML and save the file at the location of the mzTab_m_swagger.yml file, thereby replacing the original file.

You can create server and client code in a multitude of languages from the Generate Server and Generate Client menu items.

== References

This project is based on and uses code that was developed for the https://github.com/PRIDE-Utilities/jmzTab[original jmzTab project]:

http://onlinelibrary.wiley.com/doi/10.1002/pmic.201300560/abstract[Qing-Wei Xu et al., Proteomics 2014; Jun;14(11):1328-32.] http://onlinelibrary.wiley.com/doi/10.1002/pmic.201300560/pdf[PDF File.] https://www.ncbi.nlm.nih.gov/pubmed/24659499[PubMed record.]

