= mzTab 2.0 for Metabolomics Reader, Writer and Validator
Nils Hoffmann <nils.hoffmann@isas.de>

image:https://travis-ci.org/nilshoffmann/jmzTab-m.svg?branch=master["Build Status", link="https://travis-ci.org/nilshoffmann/jmzTab-m"] image:https://img.shields.io/maven-central/v/de.isas.mztab/jmztabm-cli.svg["Maven Central", link="https://search.maven.org/remotecontent?filepath=de/isas/mztab/jmztabm-cli/0.9.5/jmztabm-cli-0.9.5-bin.zip"]

This project is the reference reader, writer and validator implementation for mzTab 2.0+, based on the https://github.com/PRIDE-Utilities/jmztab[jmztab project].

The latest draft version of the mzTab spec is available https://github.com/HUPO-PSI/mzTab/blob/master/specification_document/1_1_draft_specs/mzTab_format_specification_1_1-M_draft.adoc[here].

The web-based validator application is available https://github.com/nilshoffmann/jmzTab-m-webapp[here].

== Building the project and generating client code from the command-line

In order to build the client code and run the unit tests, execute the following command from a terminal:

	./mvnw install

This generates the necessary domain specific code for a number of different languages, e.g. for Python, JAVA and R.
In general, any language and framework for which swagger-codegen has templates available may be used. For details, please 
look at the `api/pom.xml` file and at the https://github.com/swagger-api/swagger-codegen[swagger-codegen repository and documentation].

The generated code is available in the zip archives below the `api/target` directory:

. mztab-api-python
. mztab-api-r

The generated JAVA code is available in a jar archive below the `api/target` directory:

. jmztabm-api-<VERSION>.jar

The generated client libraries only contain the basic domain object code. Parsing from mzTab and writing to mzTab still need to be 
implemented separately. The library provides this functionality for JAVA in the `io` sub-project.

== Running a validation with the command-line interface
The `cli` sub-project provides a command line interface for validation of files using the mzTab 2.0 draft validator. 

NOTE: Currently, we do not plan to provide a CLI-based validator for mzTab 1.0, since that is still being provided by the original https://github.com/PRIDE-Utilities/jmzTab[jmzTab project].

After building the project as mentioned above with `./mvnw install`, the `cli/target` folder will contain the `cli-<version>-jmztabm-deployment.zip` file. Alternatively, you can download the latest 
cli zip file from Maven central: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22de.isas.mztab%22%20AND%20a%3A%22jmztabm-cli%22%20[Search for latest cli artefact] and click on "bin.zip" to download.

In order to run the validator, unzip that file, change into the unzipped folder and run

  java -jar jmztabm-cli-<VERSION>.jar

to see the available options.

To validate a particular file with a given level (one of: Info, Warn, Error, where Info includes Warn and Error), run

  java -jar jmztabm-cli-<VERSION>.jar -check inFile=examples/MTBLS263.mztab -level Info

== Running the Web Application for Validation

The validator web application code has been moved into a separate project: https://github.com/nilshoffmann/jmzTab-m-webapp
The application is available at: https://apps.lifs.isas.de/mztabvalidator

== Using the project code releases via Maven Central

The library release artifacts are available from Maven Central.
If you want to use them, add the following lines to your own Maven pom file (replacing the version with the latest one you want to use):

To use the IO libraries (reading, writing and structural and logical validation) in your own Maven projects, use the following dependency:

  <dependency>
    <groupId>de.isas.mztab</groupId>
    <artifactId>jmztabm-io</artifactId>
    <version>0.9.5</version>
  </dependency>


To use the semantic validation with the mapping file in your own Maven project, use the following dependency:

  <dependency>
    <groupId>de.isas.mztab</groupId>
    <artifactId>jmztabm-validation</artifactId>
    <version>0.9.5</version>
  </dependency>

== Using development snapshots

The library development artifacts are available as SNAPSHOT (development versions) from Sonatype's OSSRH repository. 
If you want to use them, add the following lines to your own Maven pom file:

  <repositories>
    <repository>
      <name>Sonatype Snapshot Repository</name>
      <id>oss-sonatype-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
   ...
  </repositories>

The project coordinates for the api module are 

    <dependency>
      <groupId>de.isas.mztab</groupId>
      <artifactId>jmztabm-api</artifactId>
      <version>${jmztabm.version}</version>
      <type>jar</type>
    </dependency>

and

    <dependency>
      <groupId>de.isas.mztab</groupId>
      <artifactId>jmztabm-io</artifactId>
      <version>${jmztabm.version}</version>
      <type>jar</type>
    </dependency>

for the io module, where `jmztab.version` is the version of jmztabm you wish to use, e.g. for a SNAPSHOT version:

  <properties>
    <jmztabm.version>0.9.5-SNAPSHOT</jmztabm.version>
  </properties>

as defined in the properties section of your pom file.

The SNAPSHOTS are also available from https://oss.sonatype.org/content/repositories/snapshots/de/isas/mztab/.

== Using the API programmatically

=== Reading mzTab 2.0 with structural and logical validation

The following snippet will parse an mzTabFile from a file on disk:

  File mzTabFile = new File("/path/to/my/file.mztab");
  MZTabFileParser parser = new MZTabFileParser(mzTabFile);
  //will report a maxmimum of 500 errors on Error, Warn and Info levels
  //will output errors to System.err (onto your terminal)
  parser.parse(System.err, MZTabErrorType.Level.Info, 500);
  //inspect the output of the parse and errors
  MZTabErrorList errors = parser.getErrorList();
  //access the file after parsing
  MzTab mzTab = parser.getMZTabFile();

=== Writing mzTab 2.0 with validation

The following code writes an mzTab object structure to the provided file path,
performing structural and logical validation before:

  MzTabValidatingWriter writer = new MzTabValidatingWriter();
  File f = File.createTempFile(UUID.randomUUID().toString(), ".mztab");
  Optional<List<ValidationMessage>> messages = writer.write(f.toPath(), mzTab);

You can also pass an OutputStreamWriter to the `write` method.

=== Writing mzTab 2.0 without validation

The following code writes an mzTab object structure to the provided output stream:

  MzTabNonValidatingWriter writer = new MzTabNonValidatingWriter();
  try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
      try (OutputStreamWriter osw = new OutputStreamWriter(
          baos, Charset.forName("UTF8"))) {
          writer.write(osw, mzTab);
          osw.flush();
      }
  }

Alternatively, you can also provide a File path to the `write` method.

== Editing the Swagger Spec
This project defines the structure of an mzTab document based on JSON-Schema
and Swagger https://swagger.io/.

Swagger provides many templates to generate client / server implementations
based on a Swagger yaml or json definition.

This mechanism can be used to generate the domain-specific model classes in
any of the supported languages, omitting the web-specific parts.

The https://editor.swagger.io/[Swagger editor] can be used to import the file,
edit it with assistance and preview, and export it after editing. It additionally 
supports the generation of server and client code to represent the mzTab object structure.

To launch the editor via https://www.docker.com/[Docker] on Unix, use the script
`run-swagger-editor.sh` in this directory.

The swagger API definition is in the following file: `api/src/main/resources/mzTab_m_swagger.yml`.

You can open it in the Swagger Editor via File -> Import File. If you are done editing, go to File -> Download YAML and save the file at the location of the mzTab_m_swagger.yml file, thereby replacing the original file.

You can create server and client code in a multitude of languages from the Generate Server and Generate Client menu items.

== References

This project is based on and uses code that was developed for the https://github.com/PRIDE-Utilities/jmzTab[original jmzTab project]:

http://onlinelibrary.wiley.com/doi/10.1002/pmic.201300560/abstract[Qing-Wei Xu et al., Proteomics 2014; Jun;14(11):1328-32.] http://onlinelibrary.wiley.com/doi/10.1002/pmic.201300560/pdf[PDF File.] https://www.ncbi.nlm.nih.gov/pubmed/24659499[PubMed record.]

