/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

/**
 * Specification of assay. (empty) name: A name for each assay, to serve as a list of the assays that MUST be reported in the following tables.  custom: Additional custom parameters or values for a given assay.  external_uri: An external reference uri to further information about the assay, for example via a reference to an object within an ISA-TAB file.  sample_ref: An association from a given assay to the sample analysed.  ms_run_ref: An association from a given assay to the source MS run. All assays MUST reference exactly one ms_run unless a workflow with pre-fractionation is being encoded, in which case each assay MUST reference n ms_runs where n fractions have been collected. Multiple assays SHOULD reference the same ms_run to capture multiplexed experimental designs. 
 */
@JsonPropertyOrder({
  Assay.JSON_PROPERTY_ID,
  Assay.JSON_PROPERTY_NAME,
  Assay.JSON_PROPERTY_CUSTOM,
  Assay.JSON_PROPERTY_EXTERNAL_URI,
  Assay.JSON_PROPERTY_SAMPLE_REF,
  Assay.JSON_PROPERTY_MS_RUN_REF
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Assay {
    
   /**
   * Property enumeration for Assay.
   */
  public static enum Properties {
      id("id"), 
      name("name"), 
      custom("custom"), 
      externalUri("external_uri"), 
      sampleRef("sample_ref"), 
      msRunRef("ms_run_ref");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };
  public static final String JSON_PROPERTY_ID = "id";
  
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.validation.constraints.NotNull
  private String name;

  public static final String JSON_PROPERTY_CUSTOM = "custom";
  
  private List<@Valid Parameter> custom = new ArrayList<>();

  public static final String JSON_PROPERTY_EXTERNAL_URI = "external_uri";
  
  private URI externalUri;

  public static final String JSON_PROPERTY_SAMPLE_REF = "sample_ref";
  
  private Sample sampleRef;

  public static final String JSON_PROPERTY_MS_RUN_REF = "ms_run_ref";
  @jakarta.validation.constraints.NotNull
  private List<@Valid MsRun> msRunRef = new ArrayList<>();

  public Assay() { 
  }

  public Assay id( Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId( Integer id) {
    this.id = id;
  }


  public Assay name(@jakarta.validation.constraints.NotNull String name) {
    this.name = name;
    return this;
  }

  /**
   * The assay name.
   * @return name
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.validation.constraints.NotNull String name) {
    this.name = name;
  }


  public Assay custom( List<@Valid Parameter> custom) {
    this.custom = custom;
    return this;
  }

  public Assay addCustomItem(Parameter customItem) {
    if (this.custom == null) {
      this.custom = new ArrayList<>();
    }
    this.custom.add(customItem);
    return this;
  }

  /**
   * Additional user or cv parameters.
   * @return custom
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_CUSTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getCustom() {
    return custom;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustom( List<@Valid Parameter> custom) {
    this.custom = custom;
  }


  public Assay externalUri( URI externalUri) {
    this.externalUri = externalUri;
    return this;
  }

  /**
   * An external URI to further information about this assay.
   * @return externalUri
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getExternalUri() {
    return externalUri;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalUri( URI externalUri) {
    this.externalUri = externalUri;
  }


  public Assay sampleRef(@jakarta.validation.constraints.NotNull Sample sampleRef) {
    this.sampleRef = sampleRef;
    return this;
  }

  /**
   * Get sampleRef
   * @return sampleRef
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_SAMPLE_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Sample getSampleRef() {
    return sampleRef;
  }


  @JsonProperty(value = JSON_PROPERTY_SAMPLE_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSampleRef( Sample sampleRef) {
    this.sampleRef = sampleRef;
  }


  public Assay msRunRef(@jakarta.validation.constraints.NotNull List<@Valid MsRun> msRunRef) {
    this.msRunRef = msRunRef;
    return this;
  }

  public Assay addMsRunRefItem(MsRun msRunRefItem) {
    if (this.msRunRef == null) {
      this.msRunRef = new ArrayList<>();
    }
    this.msRunRef.add(msRunRefItem);
    return this;
  }

  /**
   * The ms run(s) referenced by this assay.
   * @return msRunRef
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @Valid
  @Size(min=1)
  @JsonProperty(value = JSON_PROPERTY_MS_RUN_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid MsRun> getMsRunRef() {
    return msRunRef;
  }


  @JsonProperty(value = JSON_PROPERTY_MS_RUN_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMsRunRef(@jakarta.validation.constraints.NotNull List<@Valid MsRun> msRunRef) {
    this.msRunRef = msRunRef;
  }


  /**
   * Return true if this Assay object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Assay assay = (Assay) o;
    return Objects.equals(this.id, assay.id) &&
        Objects.equals(this.name, assay.name) &&
        Objects.equals(this.custom, assay.custom) &&
        Objects.equals(this.externalUri, assay.externalUri) &&
        Objects.equals(this.sampleRef, assay.sampleRef) &&
        Objects.equals(this.msRunRef, assay.msRunRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, custom, externalUri, sampleRef, msRunRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Assay {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    externalUri: ").append(toIndentedString(externalUri)).append("\n");
    sb.append("    sampleRef: ").append(toIndentedString(sampleRef)).append("\n");
    sb.append("    msRunRef: ").append(toIndentedString(msRunRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

