/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Defines the used unit for a column in the mzTab-M file. The format of the value has to be \\{column name}&#x3D;\\{Parameter defining the unit}. This field MUST NOT be used to define a unit for quantification columns. The unit used for small molecule quantification values MUST be set in small_molecule-quantification_unit.
 */
@JsonPropertyOrder({
  ColumnParameterMapping.JSON_PROPERTY_COLUMN_NAME,
  ColumnParameterMapping.JSON_PROPERTY_PARAM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class ColumnParameterMapping {
    
  /**
   * Property enumeration for ColumnParameterMapping.
   */
  public static enum Properties {
      columnName("column_name"), 
      param("param");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };    
    
  public static final String JSON_PROPERTY_COLUMN_NAME = "column_name";
  @jakarta.validation.constraints.NotNull
  private String columnName;

  public static final String JSON_PROPERTY_PARAM = "param";
  @jakarta.validation.constraints.NotNull
  private Parameter param;

  public ColumnParameterMapping() { 
  }

  public ColumnParameterMapping columnName(@jakarta.validation.constraints.NotNull String columnName) {
    this.columnName = columnName;
    return this;
  }

  /**
   * The fully qualified target column name.
   * @return columnName
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_COLUMN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getColumnName() {
    return columnName;
  }


  @JsonProperty(value = JSON_PROPERTY_COLUMN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumnName(@jakarta.validation.constraints.NotNull String columnName) {
    this.columnName = columnName;
  }


  public ColumnParameterMapping param(@jakarta.validation.constraints.NotNull Parameter param) {
    this.param = param;
    return this;
  }

  /**
   * Get param
   * @return param
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @Valid
  @JsonProperty(value = JSON_PROPERTY_PARAM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Parameter getParam() {
    return param;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParam(@jakarta.validation.constraints.NotNull Parameter param) {
    this.param = param;
  }


  /**
   * Return true if this ColumnParameterMapping object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColumnParameterMapping columnParameterMapping = (ColumnParameterMapping) o;
    return Objects.equals(this.columnName, columnParameterMapping.columnName) &&
        Objects.equals(this.param, columnParameterMapping.param);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnName, param);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ColumnParameterMapping {\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    param: ").append(toIndentedString(param)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

