/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Comment lines can be placed anywhere in an mzTab file. These lines must start with the three-letter code COM and are ignored by most parsers. Empty lines can also occur anywhere in an mzTab file and are ignored. 
 */
@JsonPropertyOrder({
  Comment.JSON_PROPERTY_PREFIX,
  Comment.JSON_PROPERTY_MSG,
  Comment.JSON_PROPERTY_LINE_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Comment {
    
  /**
   * Property enumeration for Comment.
   */
  public static enum Properties {
      prefix("prefix"), 
      msg("msg"), 
      lineNumber("line_number");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };

  /**
   * Gets or Sets prefix
   */
  public enum PrefixEnum {
    COM(String.valueOf("COM"));

    private String value;

    PrefixEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PrefixEnum fromValue(String value) {
      for (PrefixEnum b : PrefixEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @jakarta.validation.constraints.NotNull
  private PrefixEnum prefix = PrefixEnum.COM;

  public static final String JSON_PROPERTY_MSG = "msg";
  @jakarta.validation.constraints.NotNull
  private String msg;

  public static final String JSON_PROPERTY_LINE_NUMBER = "line_number";
  
  private Integer lineNumber;

  public Comment() { 
  }

  public Comment prefix(@jakarta.validation.constraints.NotNull PrefixEnum prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * Get prefix
   * @return prefix
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PrefixEnum getPrefix() {
    return prefix;
  }


  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrefix(@jakarta.validation.constraints.NotNull PrefixEnum prefix) {
    this.prefix = prefix;
  }


  public Comment msg(@jakarta.validation.constraints.NotNull String msg) {
    this.msg = msg;
    return this;
  }

  /**
   * Get msg
   * @return msg
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_MSG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMsg() {
    return msg;
  }


  @JsonProperty(value = JSON_PROPERTY_MSG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMsg(@jakarta.validation.constraints.NotNull String msg) {
    this.msg = msg;
  }


  public Comment lineNumber( Integer lineNumber) {
    this.lineNumber = lineNumber;
    return this;
  }

  /**
   * Get lineNumber
   * @return lineNumber
   */
  

  @JsonProperty(value = JSON_PROPERTY_LINE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLineNumber() {
    return lineNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_LINE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineNumber( Integer lineNumber) {
    this.lineNumber = lineNumber;
  }


  /**
   * Return true if this Comment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Comment comment = (Comment) o;
    return Objects.equals(this.prefix, comment.prefix) &&
        Objects.equals(this.msg, comment.msg) &&
        Objects.equals(this.lineNumber, comment.lineNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefix, msg, lineNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Comment {\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("    lineNumber: ").append(toIndentedString(lineNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

