/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URI;
import java.util.Arrays;
import java.util.Objects;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

/**
 * Specification of controlled vocabularies. label: A string describing the labels of the controlled vocabularies/ontologies used in the mzTab file as a short-hand e.g. \&quot;MS\&quot; for PSI-MS. full_name: A string describing the full names of the controlled vocabularies/ontologies used in the mzTab file. version: A string describing the version of the controlled vocabularies/ontologies used in the mzTab file. uri: A string containing the URIs of the controlled vocabularies/ontologies used in the mzTab file. 
 */
@JsonPropertyOrder({
  CV.JSON_PROPERTY_ID,
  CV.JSON_PROPERTY_LABEL,
  CV.JSON_PROPERTY_FULL_NAME,
  CV.JSON_PROPERTY_VERSION,
  CV.JSON_PROPERTY_URI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class CV {
    
  /**
   * Property enumeration for CV.
   */
  public static enum Properties {
      id("id"), 
      label("label"), 
      fullName("full_name"), 
      version("version"), 
      uri("uri");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };
  public static final String JSON_PROPERTY_ID = "id";
  
  private Integer id;

  public static final String JSON_PROPERTY_LABEL = "label";
  @jakarta.validation.constraints.NotNull
  private String label;

  public static final String JSON_PROPERTY_FULL_NAME = "full_name";
  @jakarta.validation.constraints.NotNull
  private String fullName;

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.validation.constraints.NotNull
  private String version;

  public static final String JSON_PROPERTY_URI = "uri";
  @jakarta.validation.constraints.NotNull
  private URI uri;

  public CV() { 
  }

  public CV id( Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  
  @Min(1) 
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId( Integer id) {
    this.id = id;
  }


  public CV label(@jakarta.validation.constraints.NotNull String label) {
    this.label = label;
    return this;
  }

  /**
   * The abbreviated CV label.
   * @return label
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_LABEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLabel() {
    return label;
  }


  @JsonProperty(value = JSON_PROPERTY_LABEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabel(@jakarta.validation.constraints.NotNull String label) {
    this.label = label;
  }


  public CV fullName(@jakarta.validation.constraints.NotNull String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * The full name of this CV, for humans.
   * @return fullName
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFullName() {
    return fullName;
  }


  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFullName(@jakarta.validation.constraints.NotNull String fullName) {
    this.fullName = fullName;
  }


  public CV version(@jakarta.validation.constraints.NotNull String version) {
    this.version = version;
    return this;
  }

  /**
   * The CV version used when the file was generated.
   * @return version
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@jakarta.validation.constraints.NotNull String version) {
    this.version = version;
  }


  public CV uri(@jakarta.validation.constraints.NotNull URI uri) {
    this.uri = uri;
    return this;
  }

  /**
   * A URI to the CV definition.
   * @return uri
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @Valid
  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getUri() {
    return uri;
  }


  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUri(@jakarta.validation.constraints.NotNull URI uri) {
    this.uri = uri;
  }


  /**
   * Return true if this CV object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CV CV = (CV) o;
    return Objects.equals(this.id, CV.id) &&
        Objects.equals(this.label, CV.label) &&
        Objects.equals(this.fullName, CV.fullName) &&
        Objects.equals(this.version, CV.version) &&
        Objects.equals(this.uri, CV.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, fullName, version, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CV {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

