/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Specification of databases. (empty): The description of databases used. For cases, where a known database has not been used for identification, a userParam SHOULD be inserted to describe any identification performed e.g. de novo. If no identification has been performed at all then \&quot;no database\&quot; should be inserted followed by null. prefix: The prefix used in the “identifier” column of data tables. For the “no database” case \&quot;null\&quot; must be used. version: The database version is mandatory where identification has been performed. This may be a formal version number e.g. “1.4.1”, a date of access “2016-10-27” (ISO-8601 format) or “Unknown” if there is no suitable version that can be annotated. uri: The URI to the database. For the “no database” case, \&quot;null\&quot; must be reported. 
 */
@JsonPropertyOrder({
  Database.JSON_PROPERTY_ID,
  Database.JSON_PROPERTY_PARAM,
  Database.JSON_PROPERTY_PREFIX,
  Database.JSON_PROPERTY_VERSION,
  Database.JSON_PROPERTY_URI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Database {

  /**
   * Property enumeration for Database.
   */
  public static enum Properties {
      id("id"), 
      param("param"), 
      prefix("prefix"), 
      version("version"), 
      uri("uri");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };
  
  public static final String JSON_PROPERTY_ID = "id";
  
  private Integer id;

  public static final String JSON_PROPERTY_PARAM = "param";
  @jakarta.validation.constraints.NotNull
  private Parameter param;

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @jakarta.validation.constraints.NotNull
  private String prefix = "null";

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.validation.constraints.NotNull
  private String version;

  public static final String JSON_PROPERTY_URI = "uri";
  @jakarta.validation.constraints.NotNull
  private URI uri;

  public Database() { 
  }

  public Database id( Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId( Integer id) {
    this.id = id;
  }


  public Database param(@jakarta.validation.constraints.NotNull Parameter param) {
    this.param = param;
    return this;
  }

  /**
   * Get param
   * @return param
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @Valid
  @JsonProperty(value = JSON_PROPERTY_PARAM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Parameter getParam() {
    return param;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParam(@jakarta.validation.constraints.NotNull Parameter param) {
    this.param = param;
  }


  public Database prefix(@jakarta.validation.constraints.NotNull String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * The database prefix.
   * @return prefix
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPrefix() {
    return prefix;
  }


  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrefix(@jakarta.validation.constraints.NotNull String prefix) {
    this.prefix = prefix;
  }


  public Database version(@jakarta.validation.constraints.NotNull String version) {
    this.version = version;
    return this;
  }

  /**
   * The database version.
   * @return version
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@jakarta.validation.constraints.NotNull String version) {
    this.version = version;
  }


  public Database uri(@jakarta.validation.constraints.NotNull URI uri) {
    this.uri = uri;
    return this;
  }

  /**
   * The URI to the online database.
   * @return uri
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @Valid
  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getUri() {
    return uri;
  }


  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUri(@jakarta.validation.constraints.NotNull URI uri) {
    this.uri = uri;
  }


  /**
   * Return true if this Database object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Database database = (Database) o;
    return Objects.equals(this.id, database.id) &&
        Objects.equals(this.param, database.param) &&
        Objects.equals(this.prefix, database.prefix) &&
        Objects.equals(this.version, database.version) &&
        Objects.equals(this.uri, database.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, param, prefix, version, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Database {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    param: ").append(toIndentedString(param)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

