/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The mzTab-M profile a file conforms to. The profile declares which of the four
 * tables (metadata, small molecule summary, small molecule feature, small
 * molecule evidence) are contained in a file:
 * <ul>
 * <li>{@code M} - metadata section only</li>
 * <li>{@code M+S} - metadata and small molecule summary section</li>
 * <li>{@code M+F} - metadata and small molecule feature section</li>
 * <li>{@code M+F+E} - metadata, small molecule feature and small molecule evidence section</li>
 * <li>{@code M+S+F+E} - metadata, small molecule summary, feature and evidence section (the classic full file)</li>
 * </ul>
 */
public enum MzTabProfile {

  M(String.valueOf("M")),

  M_S(String.valueOf("M+S")),

  M_F(String.valueOf("M+F")),

  M_F_E(String.valueOf("M+F+E")),

  M_S_F_E(String.valueOf("M+S+F+E"));

  private String value;

  MzTabProfile(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MzTabProfile fromValue(String value) {
    for (MzTabProfile b : MzTabProfile.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Lenient lookup that returns {@code null} instead of throwing when the given
   * value does not correspond to any known profile. Useful for validation where
   * an unknown value should be reported as an error rather than aborting parsing.
   *
   * @param value the string value, e.g. "M+S+F+E"
   * @return the matching {@link MzTabProfile} or {@code null} if none matches
   */
  public static MzTabProfile findProfile(String value) {
    if (value == null) {
      return null;
    }
    for (MzTabProfile b : MzTabProfile.values()) {
      if (b.value.equals(value.trim())) {
        return b;
      }
    }
    return null;
  }
}
