/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Additional columns can be added to the end of the small molecule table. These column headers MUST start with the prefix “opt_” followed by the {identifier} of the object they reference: assay, study variable, MS run or “global” (if the value relates to all replicates). Column names MUST only contain the following characters: ‘A’-‘Z’, ‘a’-‘z’, ‘0’-‘9’, ‘’, ‘-’, ‘[’, ‘]’, and ‘:’. CV parameter accessions MAY be used for optional columns following the format: opt{identifier}_cv_{accession}_\\{parameter name}. Spaces within the parameter’s name MUST be replaced by ‘_’. 
 */
@JsonPropertyOrder({
  OptColumnMapping.JSON_PROPERTY_IDENTIFIER,
  OptColumnMapping.JSON_PROPERTY_PARAM,
  OptColumnMapping.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class OptColumnMapping {

  /**
   * Property enumeration for OptColumnMapping.
   */
  public static enum Properties {
      identifier("identifier"), 
      param("param"), 
      value("value");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };
  
  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.validation.constraints.NotNull
  private String identifier;

  public static final String JSON_PROPERTY_PARAM = "param";
  
  private Parameter param;

  public static final String JSON_PROPERTY_VALUE = "value";
  
  private String value;

  public OptColumnMapping() { 
  }

  public OptColumnMapping identifier(@jakarta.validation.constraints.NotNull String identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * The fully qualified column name.
   * @return identifier
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_IDENTIFIER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIdentifier() {
    return identifier;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTIFIER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifier(@jakarta.validation.constraints.NotNull String identifier) {
    this.identifier = identifier;
  }


  public OptColumnMapping param( Parameter param) {
    this.param = param;
    return this;
  }

  /**
   * Get param
   * @return param
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_PARAM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getParam() {
    return param;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParam( Parameter param) {
    this.param = param;
  }


  public OptColumnMapping value( String value) {
    this.value = value;
    return this;
  }

  /**
   * The value for this column in a particular row.
   * @return value
   */
  

  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue( String value) {
    this.value = value;
  }


  /**
   * Return true if this OptColumnMapping object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptColumnMapping optColumnMapping = (OptColumnMapping) o;
    return Objects.equals(this.identifier, optColumnMapping.identifier) &&
        Objects.equals(this.param, optColumnMapping.param) &&
        Objects.equals(this.value, optColumnMapping.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, param, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OptColumnMapping {\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    param: ").append(toIndentedString(param)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

