/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * mzTab makes use of CV parameters. As mzTab is expected to be used in several experimental environments where parameters might not yet be available for the generated scores etc. all parameters can either report CV parameters or user parameters that only contain a name and a value. Parameters are always reported as [CV label, accession, name, value]. Any field that is not available MUST be left empty. 
 */
@JsonPropertyOrder({
  Parameter.JSON_PROPERTY_CV_LABEL,
  Parameter.JSON_PROPERTY_CV_ACCESSION,
  Parameter.JSON_PROPERTY_NAME,
  Parameter.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Parameter {

  /**
   * Property enumeration for Parameter.
   */
  public static enum Properties {
      cvLabel("cv_label"), 
      cvAccession("cv_accession"), 
      name("name"), 
      value("value");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };

  public static final String JSON_PROPERTY_CV_LABEL = "cv_label";
  
  private String cvLabel = "";

  public static final String JSON_PROPERTY_CV_ACCESSION = "cv_accession";
  
  private String cvAccession = "";

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.validation.constraints.NotNull
  private String name;

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.validation.constraints.NotNull
  private String value = "";

  public Parameter() { 
  }


  public Parameter cvLabel( String cvLabel) {
    this.cvLabel = cvLabel;
    return this;
  }

  /**
   * Get cvLabel
   * @return cvLabel
   */
  

  @JsonProperty(value = JSON_PROPERTY_CV_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCvLabel() {
    return cvLabel;
  }


  @JsonProperty(value = JSON_PROPERTY_CV_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCvLabel( String cvLabel) {
    this.cvLabel = cvLabel;
  }


  public Parameter cvAccession( String cvAccession) {
    this.cvAccession = cvAccession;
    return this;
  }

  /**
   * Get cvAccession
   * @return cvAccession
   */
  

  @JsonProperty(value = JSON_PROPERTY_CV_ACCESSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCvAccession() {
    return cvAccession;
  }


  @JsonProperty(value = JSON_PROPERTY_CV_ACCESSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCvAccession( String cvAccession) {
    this.cvAccession = cvAccession;
  }


  public Parameter name(@jakarta.validation.constraints.NotNull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.validation.constraints.NotNull String name) {
    this.name = name;
  }


  public Parameter value(@jakarta.validation.constraints.NotNull String value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@jakarta.validation.constraints.NotNull String value) {
    this.value = value;
  }


  /**
   * Return true if this Parameter object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Parameter parameter = (Parameter) o;
    return Objects.equals(this.cvLabel, parameter.cvLabel) &&
        Objects.equals(this.cvAccession, parameter.cvAccession) &&
        Objects.equals(this.name, parameter.name) &&
        Objects.equals(this.value, parameter.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cvLabel, cvAccession, name, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Parameter {\n");
    sb.append("    cvLabel: ").append(toIndentedString(cvLabel)).append("\n");
    sb.append("    cvAccession: ").append(toIndentedString(cvAccession)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

