/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * A publication item, defined by a qualifier and a native accession, e.g. pubmed id.
 */
@JsonPropertyOrder({
  PublicationItem.JSON_PROPERTY_TYPE,
  PublicationItem.JSON_PROPERTY_ACCESSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class PublicationItem {

  /**
   * Property enumeration for PublicationItem.
   */
  public static enum Properties {
      type("type"), 
      accession("accession");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };
  
  /**
   * The type qualifier of this publication item.
   */
  public enum TypeEnum {
    DOI(String.valueOf("doi")),
    
    PUBMED(String.valueOf("pubmed")),
    
    URI(String.valueOf("uri"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
      //throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.validation.constraints.NotNull
  private TypeEnum type = TypeEnum.DOI;

  public static final String JSON_PROPERTY_ACCESSION = "accession";
  @jakarta.validation.constraints.NotNull
  private String accession;

  public PublicationItem() { 
  }

  public PublicationItem type(@jakarta.validation.constraints.NotNull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The type qualifier of this publication item.
   * @return type
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.validation.constraints.NotNull TypeEnum type) {
    this.type = type;
  }


  public PublicationItem accession(@jakarta.validation.constraints.NotNull String accession) {
    this.accession = accession;
    return this;
  }

  /**
   * The native accession id for this publication item.
   * @return accession
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_ACCESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccession() {
    return accession;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccession(@jakarta.validation.constraints.NotNull String accession) {
    this.accession = accession;
  }


  /**
   * Return true if this PublicationItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicationItem publicationItem = (PublicationItem) o;
    return Objects.equals(this.type, publicationItem.type) &&
        Objects.equals(this.accession, publicationItem.accession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, accession);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicationItem {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    accession: ").append(toIndentedString(accession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

