/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Specification of sample. (empty) name: A name for each sample to serve as a list of the samples that MUST be reported in the following tables. Samples MUST be reported if a statistical design is being captured (i.e. bio or tech replicates). If the type of replicates are not known, samples SHOULD NOT be reported.  species: The respective species of the samples analysed. For more complex cases, such as metagenomics, optional columns and userParams should be used.  tissue: The respective tissue(s) of the sample.  cell_type: The respective cell type(s) of the sample.  disease: The respective disease(s) of the sample.  description: A human readable description of the sample.  custom: Custom parameters describing the sample&#39;s additional properties. Dates MUST be provided in ISO-8601 format. 
 */
@JsonPropertyOrder({
  Sample.JSON_PROPERTY_ID,
  Sample.JSON_PROPERTY_NAME,
  Sample.JSON_PROPERTY_CUSTOM,
  Sample.JSON_PROPERTY_SPECIES,
  Sample.JSON_PROPERTY_TISSUE,
  Sample.JSON_PROPERTY_CELL_TYPE,
  Sample.JSON_PROPERTY_DISEASE,
  Sample.JSON_PROPERTY_DESCRIPTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Sample {

  /**
   * Property enumeration for Sample.
   */
  public static enum Properties {
      id("id"), 
      name("name"), 
      custom("custom"), 
      species("species"), 
      tissue("tissue"), 
      cellType("cell_type"), 
      disease("disease"), 
      description("description");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };
  
  public static final String JSON_PROPERTY_ID = "id";
  
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  
  private String name;

  public static final String JSON_PROPERTY_CUSTOM = "custom";
  
  private List<@Valid Parameter> custom = new ArrayList<>();

  public static final String JSON_PROPERTY_SPECIES = "species";
  
  private List<@Valid Parameter> species = new ArrayList<>();

  public static final String JSON_PROPERTY_TISSUE = "tissue";
  
  private List<@Valid Parameter> tissue = new ArrayList<>();

  public static final String JSON_PROPERTY_CELL_TYPE = "cell_type";
  
  private List<@Valid Parameter> cellType = new ArrayList<>();

  public static final String JSON_PROPERTY_DISEASE = "disease";
  
  private List<@Valid Parameter> disease = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  
  private String description;

  public Sample() { 
  }

  public Sample id( Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  
  @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId( Integer id) {
    this.id = id;
  }


  public Sample name( String name) {
    this.name = name;
    return this;
  }

  /**
   * The sample&#39;s name.
   * @return name
   */
  

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName( String name) {
    this.name = name;
  }


  public Sample custom( List<@Valid Parameter> custom) {
    this.custom = custom;
    return this;
  }

  public Sample addCustomItem(Parameter customItem) {
    if (this.custom == null) {
      this.custom = new ArrayList<>();
    }
    this.custom.add(customItem);
    return this;
  }

  /**
   * Additional user or cv parameters.
   * @return custom
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_CUSTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getCustom() {
    return custom;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustom( List<@Valid Parameter> custom) {
    this.custom = custom;
  }


  public Sample species( List<@Valid Parameter> species) {
    this.species = species;
    return this;
  }

  public Sample addSpeciesItem(Parameter speciesItem) {
    if (this.species == null) {
      this.species = new ArrayList<>();
    }
    this.species.add(speciesItem);
    return this;
  }

  /**
   * Biological species information on the sample.
   * @return species
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_SPECIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getSpecies() {
    return species;
  }


  @JsonProperty(value = JSON_PROPERTY_SPECIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecies( List<@Valid Parameter> species) {
    this.species = species;
  }


  public Sample tissue( List<@Valid Parameter> tissue) {
    this.tissue = tissue;
    return this;
  }

  public Sample addTissueItem(Parameter tissueItem) {
    if (this.tissue == null) {
      this.tissue = new ArrayList<>();
    }
    this.tissue.add(tissueItem);
    return this;
  }

  /**
   * Biological tissue information on the sample.
   * @return tissue
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_TISSUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getTissue() {
    return tissue;
  }


  @JsonProperty(value = JSON_PROPERTY_TISSUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTissue( List<@Valid Parameter> tissue) {
    this.tissue = tissue;
  }


  public Sample cellType( List<@Valid Parameter> cellType) {
    this.cellType = cellType;
    return this;
  }

  public Sample addCellTypeItem(Parameter cellTypeItem) {
    if (this.cellType == null) {
      this.cellType = new ArrayList<>();
    }
    this.cellType.add(cellTypeItem);
    return this;
  }

  /**
   * Biological cell type information on the sample.
   * @return cellType
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_CELL_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getCellType() {
    return cellType;
  }


  @JsonProperty(value = JSON_PROPERTY_CELL_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCellType( List<@Valid Parameter> cellType) {
    this.cellType = cellType;
  }


  public Sample disease( List<@Valid Parameter> disease) {
    this.disease = disease;
    return this;
  }

  public Sample addDiseaseItem(Parameter diseaseItem) {
    if (this.disease == null) {
      this.disease = new ArrayList<>();
    }
    this.disease.add(diseaseItem);
    return this;
  }

  /**
   * Disease information on the sample.
   * @return disease
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_DISEASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getDisease() {
    return disease;
  }


  @JsonProperty(value = JSON_PROPERTY_DISEASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisease( List<@Valid Parameter> disease) {
    this.disease = disease;
  }


  public Sample description( String description) {
    this.description = description;
    return this;
  }

  /**
   * A free form description of the sample.
   * @return description
   */
  

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription( String description) {
    this.description = description;
  }


  /**
   * Return true if this Sample object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sample sample = (Sample) o;
    return Objects.equals(this.id, sample.id) &&
        Objects.equals(this.name, sample.name) &&
        Objects.equals(this.custom, sample.custom) &&
        Objects.equals(this.species, sample.species) &&
        Objects.equals(this.tissue, sample.tissue) &&
        Objects.equals(this.cellType, sample.cellType) &&
        Objects.equals(this.disease, sample.disease) &&
        Objects.equals(this.description, sample.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, custom, species, tissue, cellType, disease, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sample {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    species: ").append(toIndentedString(species)).append("\n");
    sb.append("    tissue: ").append(toIndentedString(tissue)).append("\n");
    sb.append("    cellType: ").append(toIndentedString(cellType)).append("\n");
    sb.append("    disease: ").append(toIndentedString(disease)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

