/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * A list of parameters describing a sample processing, preparation or handling step similar to a biological or analytical methods report. The order of the sample_processing items should reflect the order these processing steps were performed in. If multiple parameters are given for a step these MUST be separated by a “|”. If derivatization was performed, it MUST be reported here as a general step, e.g. &#39;silylation&#39; and the actual derivatization agens MUST be specified in the Section 6.2.54 part.       
 */
@JsonPropertyOrder({
  SampleProcessing.JSON_PROPERTY_ID,
  SampleProcessing.JSON_PROPERTY_SAMPLE_PROCESSING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class SampleProcessing {

  /**
   * Property enumeration for SampleProcessing.
   */
  public static enum Properties {
      id("id"), 
      sampleProcessing("sampleProcessing");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };
  
  public static final String JSON_PROPERTY_ID = "id";
  
  private Integer id;

  public static final String JSON_PROPERTY_SAMPLE_PROCESSING = "sampleProcessing";
  
  private List<@Valid Parameter> sampleProcessing = new ArrayList<>();

  public SampleProcessing() { 
  }

  public SampleProcessing id( Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  
  @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId( Integer id) {
    this.id = id;
  }


  public SampleProcessing sampleProcessing( List<@Valid Parameter> sampleProcessing) {
    this.sampleProcessing = sampleProcessing;
    return this;
  }

  public SampleProcessing addSampleProcessingItem(Parameter sampleProcessingItem) {
    if (this.sampleProcessing == null) {
      this.sampleProcessing = new ArrayList<>();
    }
    this.sampleProcessing.add(sampleProcessingItem);
    return this;
  }

  /**
   * Parameters specifiying sample processing that was applied within one step.
   * @return sampleProcessing
   */
  
  @Valid
  @JsonProperty(value = JSON_PROPERTY_SAMPLE_PROCESSING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getSampleProcessing() {
    return sampleProcessing;
  }


  @JsonProperty(value = JSON_PROPERTY_SAMPLE_PROCESSING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSampleProcessing( List<@Valid Parameter> sampleProcessing) {
    this.sampleProcessing = sampleProcessing;
  }


  /**
   * Return true if this SampleProcessing object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SampleProcessing sampleProcessing = (SampleProcessing) o;
    return Objects.equals(this.id, sampleProcessing.id) &&
        Objects.equals(this.sampleProcessing, sampleProcessing.sampleProcessing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sampleProcessing);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SampleProcessing {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sampleProcessing: ").append(toIndentedString(sampleProcessing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

