/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: nils.hoffmann@cebitec.uni-bielefeld.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.lifstools.mztab2.model.MsRun;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Reference to a spectrum in a spectrum file, for example a fragmentation spectrum has been used to support the identification. If a separate spectrum file has been used for fragmentation spectrum, this MUST be reported in the metadata section as additional ms_runs. The reference must be in the format ms_run[1-n]:{SPECTRA_REF} where SPECTRA_REF MUST follow the format defined in 5.2 (including references to chromatograms where these are used to inform identification). Multiple spectra MUST be referenced using a “|” delimited list for the (rare) cases in which search engines have combined or aggregated multiple spectra in advance of the search to make identifications.  If a fragmentation spectrum has not been used, the value should indicate the ms_run to which is identification is mapped e.g. “ms_run[1]”. 
 */
@JsonPropertyOrder({
  SpectraRef.JSON_PROPERTY_MS_RUN,
  SpectraRef.JSON_PROPERTY_REFERENCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-08T17:12:00.460651+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class SpectraRef {

  /**
   * Property enumeration for SpectraRef.
   */
  public static enum Properties {
      msRun("ms_run"), 
      reference("reference");

    private final String propertyName;

    private Properties(String propertyName) {
      this.propertyName = propertyName;
    }

    public String getPropertyName() {
      return propertyName;
    }

    public String toString() {
      return propertyName;
    }

    public String toUpper() {
      return propertyName.toUpperCase();
    }

    public static Properties of(String value) {
      if(value==null) {
        throw new NullPointerException("Argument value must not be null!");
      }
      return Arrays.asList(Properties.values()).stream().filter(m -> m.propertyName.equals(value.toLowerCase())).findAny().orElseThrow(IllegalArgumentException::new);
    }
  };
  
  public static final String JSON_PROPERTY_MS_RUN = "ms_run";
  @jakarta.validation.constraints.NotNull
  private MsRun msRun;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  @jakarta.validation.constraints.NotNull
  private String reference;

  public SpectraRef() { 
  }

  public SpectraRef msRun(@jakarta.validation.constraints.NotNull MsRun msRun) {
    this.msRun = msRun;
    return this;
  }

  /**
   * Get msRun
   * @return msRun
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @Valid
  @JsonProperty(value = JSON_PROPERTY_MS_RUN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MsRun getMsRun() {
    return msRun;
  }


  @JsonProperty(value = JSON_PROPERTY_MS_RUN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMsRun(@jakarta.validation.constraints.NotNull MsRun msRun) {
    this.msRun = msRun;
  }


  public SpectraRef reference(@jakarta.validation.constraints.NotNull String reference) {
    this.reference = reference;
    return this;
  }

  /**
   * The (vendor-dependendent) reference string to the actual mass spectrum. 
   * @return reference
   */
  @jakarta.validation.constraints.NotNull
  @NotNull
  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getReference() {
    return reference;
  }


  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReference(@jakarta.validation.constraints.NotNull String reference) {
    this.reference = reference;
  }


  /**
   * Return true if this SpectraRef object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpectraRef spectraRef = (SpectraRef) o;
    return Objects.equals(this.msRun, spectraRef.msRun) &&
        Objects.equals(this.reference, spectraRef.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msRun, reference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpectraRef {\n");
    sb.append("    msRun: ").append(toIndentedString(msRun)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

