/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Assay;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Specification of study_variable. (empty) name: A name for each study variable (experimental condition or factor), to serve as a list of the study variables that MUST be reported in the following tables. For software that does not capture study variables, a single study variable MUST be reported, linking to all assays. This single study variable MUST have the identifier “undefined“. assay_refs: Bar-separated references to the IDs of assays grouped in the study variable. average_function: The function used to calculate the study variable quantification value and the operation used is not arithmetic mean (default) e.g. “geometric mean”, “median”. The 1-n refers to different study variables. variation_function: The function used to calculate the study variable quantification variation value if it is reported and the operation used is not coefficient of variation (default) e.g. “standard error”. description: A textual description of the study variable. 
 */
@JsonPropertyOrder({
  StudyVariable.JSON_PROPERTY_ID,
  StudyVariable.JSON_PROPERTY_NAME,
  StudyVariable.JSON_PROPERTY_ASSAY_REFS,
  StudyVariable.JSON_PROPERTY_AVERAGE_FUNCTION,
  StudyVariable.JSON_PROPERTY_VARIATION_FUNCTION,
  StudyVariable.JSON_PROPERTY_DESCRIPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:34:38.183974+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class StudyVariable {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_ASSAY_REFS = "assay_refs";
  @jakarta.annotation.Nullable
  private List<@Valid Assay> assayRefs = new ArrayList<>();

  public static final String JSON_PROPERTY_AVERAGE_FUNCTION = "average_function";
  @jakarta.annotation.Nullable
  private Parameter averageFunction;

  public static final String JSON_PROPERTY_VARIATION_FUNCTION = "variation_function";
  @jakarta.annotation.Nullable
  private Parameter variationFunction;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public StudyVariable() {
  }

  public StudyVariable id(@jakarta.annotation.Nonnull Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
  }

  public StudyVariable name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The study variable name.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public StudyVariable assayRefs(@jakarta.annotation.Nullable List<@Valid Assay> assayRefs) {
    
    this.assayRefs = assayRefs;
    return this;
  }

  public StudyVariable addAssayRefsItem(Assay assayRefsItem) {
    if (this.assayRefs == null) {
      this.assayRefs = new ArrayList<>();
    }
    this.assayRefs.add(assayRefsItem);
    return this;
  }

  /**
   * The assays referenced by this study variable.
   * @return assayRefs
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_ASSAY_REFS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid Assay> getAssayRefs() {
    return assayRefs;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSAY_REFS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssayRefs(@jakarta.annotation.Nullable List<@Valid Assay> assayRefs) {
    this.assayRefs = assayRefs;
  }

  public StudyVariable averageFunction(@jakarta.annotation.Nullable Parameter averageFunction) {
    
    this.averageFunction = averageFunction;
    return this;
  }

  /**
   * Get averageFunction
   * @return averageFunction
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_AVERAGE_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Parameter getAverageFunction() {
    return averageFunction;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageFunction(@jakarta.annotation.Nullable Parameter averageFunction) {
    this.averageFunction = averageFunction;
  }

  public StudyVariable variationFunction(@jakarta.annotation.Nullable Parameter variationFunction) {
    
    this.variationFunction = variationFunction;
    return this;
  }

  /**
   * Get variationFunction
   * @return variationFunction
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_VARIATION_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Parameter getVariationFunction() {
    return variationFunction;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIATION_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariationFunction(@jakarta.annotation.Nullable Parameter variationFunction) {
    this.variationFunction = variationFunction;
  }

  public StudyVariable description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * A free-form description of this study variable.
   * @return description
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudyVariable studyVariable = (StudyVariable) o;
    return Objects.equals(this.id, studyVariable.id) &&
        Objects.equals(this.name, studyVariable.name) &&
        Objects.equals(this.assayRefs, studyVariable.assayRefs) &&
        Objects.equals(this.averageFunction, studyVariable.averageFunction) &&
        Objects.equals(this.variationFunction, studyVariable.variationFunction) &&
        Objects.equals(this.description, studyVariable.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, assayRefs, averageFunction, variationFunction, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudyVariable {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    assayRefs: ").append(toIndentedString(assayRefs)).append("\n");
    sb.append("    averageFunction: ").append(toIndentedString(averageFunction)).append("\n");
    sb.append("    variationFunction: ").append(toIndentedString(variationFunction)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

