/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Specification of study_variable_group. (empty) name/parameter: A parameter defining the group to which study variables belong. This allows grouping of related study variables that belong to the same experimental design factor in multi-factorial designs. The parameter can be either a CV Parameter (e.g., [OBI, OBI:0001667, organism development stage, ]) or a user-defined parameter (e.g., [,,sex,]). For software that does not capture study variables, a single study_variable_group MUST be reported, linking to the single study variable, and MUST have the identifier \&quot;undefined\&quot;. Added in mzTab-M 2.1. description: A textual description of the study variable group. type: The statistical type of the group variable, which determines how the values should be interpreted in a statistical analysis context. The type MUST be a term from the STATO ontology, and SHOULD be one of [STATO, STATO:0000252, categorical variable], [STATO, STATO:0000228, ordinal variable], or [STATO, STATO:0000251, continuous variable]. datatype: The datatype of the group variable, used to disambiguate how the associated values are encoded and parsed. Optional, but producers SHOULD provide it to simplify interpretation by downstream consumers. Supported values are xsd:string, xsd:integer, xsd:decimal, xsd:boolean, xsd:date, xsd:time, xsd:dateTime, and xsd:anyURI. Date, time and dateTime values MUST be encoded in ISO 8601 format. unit: An optional parameter specifying the unit of the study variable group (e.g., day, hour, concentration, etc.). 
 */
@JsonPropertyOrder({
  StudyVariableGroup.JSON_PROPERTY_ID,
  StudyVariableGroup.JSON_PROPERTY_PARAMETER,
  StudyVariableGroup.JSON_PROPERTY_DESCRIPTION,
  StudyVariableGroup.JSON_PROPERTY_TYPE,
  StudyVariableGroup.JSON_PROPERTY_DATATYPE,
  StudyVariableGroup.JSON_PROPERTY_UNIT,
  StudyVariableGroup.JSON_PROPERTY_STUDY_VARIABLE_REFS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:34:38.183974+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class StudyVariableGroup {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_PARAMETER = "parameter";
  @jakarta.annotation.Nonnull
  private Parameter parameter;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private Parameter type;

  public static final String JSON_PROPERTY_DATATYPE = "datatype";
  @jakarta.annotation.Nullable
  private String datatype;

  public static final String JSON_PROPERTY_UNIT = "unit";
  @jakarta.annotation.Nullable
  private Parameter unit;

  public static final String JSON_PROPERTY_STUDY_VARIABLE_REFS = "study_variable_refs";
  @jakarta.annotation.Nullable
  private List<@Valid StudyVariable> studyVariableRefs = new ArrayList<>();

  public StudyVariableGroup() {
  }

  public StudyVariableGroup id(@jakarta.annotation.Nonnull Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique identifier for this study variable group.
   * minimum: 1
   * @return id
   */
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
  }

  public StudyVariableGroup parameter(@jakarta.annotation.Nonnull Parameter parameter) {
    
    this.parameter = parameter;
    return this;
  }

  /**
   * A CV or user parameter defining the study variable group.
   * @return parameter
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PARAMETER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Parameter getParameter() {
    return parameter;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAMETER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParameter(@jakarta.annotation.Nonnull Parameter parameter) {
    this.parameter = parameter;
  }

  public StudyVariableGroup description(@jakarta.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * A textual description of the study variable group.
   * @return description
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@jakarta.annotation.Nonnull String description) {
    this.description = description;
  }

  public StudyVariableGroup type(@jakarta.annotation.Nullable Parameter type) {
    
    this.type = type;
    return this;
  }

  /**
   * The statistical type of the group variable, which determines how the values should be interpreted in a statistical analysis context. The type MUST be a term from the STATO ontology, and SHOULD be one of the examples below. [STATO, STATO:0000252, categorical variable] is a variable that can only assume a finite number of values without inherent ordering. [STATO, STATO:0000228, ordinal variable] is an ordered variable where the sequence matters but intervals between levels are undefined. These values represent categories with a defined sequence or ranking. [STATO, STATO:0000251, continuous variable] is a variable that can take any value within a range on a continuous scale. 
   * @return type
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Parameter getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable Parameter type) {
    this.type = type;
  }

  public StudyVariableGroup datatype(@jakarta.annotation.Nullable String datatype) {
    
    this.datatype = datatype;
    return this;
  }

  /**
   * The datatype of the group variable, used to disambiguate how the associated values are encoded and parsed in mzTab-M files and how they could be handled in programming languages. Optional, but producers of mzTab-M 2.1.0 SHOULD provide a value to simplify interpretation by downstream consumers. Supported values are xsd:string, xsd:integer, xsd:decimal, xsd:boolean, xsd:date, xsd:time, xsd:dateTime, and xsd:anyURI. Date, time and dateTime values MUST be encoded in ISO 8601 format. 
   * @return datatype
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_DATATYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDatatype() {
    return datatype;
  }


  @JsonProperty(value = JSON_PROPERTY_DATATYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatatype(@jakarta.annotation.Nullable String datatype) {
    this.datatype = datatype;
  }

  public StudyVariableGroup unit(@jakarta.annotation.Nullable Parameter unit) {
    
    this.unit = unit;
    return this;
  }

  /**
   * An optional parameter specifying the unit of the study variable group (e.g., day, hour, concentration, etc.).
   * @return unit
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_UNIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Parameter getUnit() {
    return unit;
  }


  @JsonProperty(value = JSON_PROPERTY_UNIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnit(@jakarta.annotation.Nullable Parameter unit) {
    this.unit = unit;
  }

  public StudyVariableGroup studyVariableRefs(@jakarta.annotation.Nullable List<@Valid StudyVariable> studyVariableRefs) {

    this.studyVariableRefs = studyVariableRefs;
    return this;
  }

  public StudyVariableGroup addStudyVariableRefsItem(StudyVariable studyVariableRefsItem) {
    if (this.studyVariableRefs == null) {
      this.studyVariableRefs = new ArrayList<>();
    }
    this.studyVariableRefs.add(studyVariableRefsItem);
    return this;
  }

  /**
   * The study variables that belong to this study variable group.
   * @return studyVariableRefs
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_STUDY_VARIABLE_REFS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid StudyVariable> getStudyVariableRefs() {
    return studyVariableRefs;
  }


  @JsonProperty(value = JSON_PROPERTY_STUDY_VARIABLE_REFS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStudyVariableRefs(@jakarta.annotation.Nullable List<@Valid StudyVariable> studyVariableRefs) {
    this.studyVariableRefs = studyVariableRefs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudyVariableGroup studyVariableGroup = (StudyVariableGroup) o;
    return Objects.equals(this.id, studyVariableGroup.id) &&
        Objects.equals(this.parameter, studyVariableGroup.parameter) &&
        Objects.equals(this.description, studyVariableGroup.description) &&
        Objects.equals(this.type, studyVariableGroup.type) &&
        Objects.equals(this.datatype, studyVariableGroup.datatype) &&
        Objects.equals(this.unit, studyVariableGroup.unit) &&
        Objects.equals(this.studyVariableRefs, studyVariableGroup.studyVariableRefs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parameter, description, type, datatype, unit, studyVariableRefs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudyVariableGroup {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parameter: ").append(toIndentedString(parameter)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    datatype: ").append(toIndentedString(datatype)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    studyVariableRefs: ").append(toIndentedString(studyVariableRefs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

